name: Build and Test Docker

on:
  push:
    branches: [ main, flask-backend, json-version ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the image
      - name: Build Docker image
        run: docker build ./backend -t simplelinks:test

      # Run container to verify it works
      - name: Run container
        run: |
          docker run -d -p 5000:5000 --name simplelinks simplelinks:test
          sleep 5
          curl -f http://localhost:5000/ || (docker logs simplelinks && exit 1)
